name: Build App

on:
  push:
    branches:
      - dev-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: android

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      working-directory: android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
